// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrf_O6V-JRPonreu6F7FiHHj-Z6gPq2IM',
    appId: '1:173771432771:web:81e25f3e7073e33a8045f6',
    messagingSenderId: '173771432771',
    projectId: 'teacherapp-f0907',
    authDomain: 'teacherapp-f0907.firebaseapp.com',
    storageBucket: 'teacherapp-f0907.appspot.com',
    measurementId: 'G-YXWLPHRP83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP670PD2Xj33M41hZbsqi0q2WqLKBgcyc',
    appId: '1:173771432771:android:29ff16c366f0a1d78045f6',
    messagingSenderId: '173771432771',
    projectId: 'teacherapp-f0907',
    storageBucket: 'teacherapp-f0907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ5fh7NHOY5IAM5unf0V1YlidCbdW0qqI',
    appId: '1:173771432771:ios:aa050afdd66555b68045f6',
    messagingSenderId: '173771432771',
    projectId: 'teacherapp-f0907',
    storageBucket: 'teacherapp-f0907.appspot.com',
    iosBundleId: 'com.example.teacherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ5fh7NHOY5IAM5unf0V1YlidCbdW0qqI',
    appId: '1:173771432771:ios:d630966f8fa67cc08045f6',
    messagingSenderId: '173771432771',
    projectId: 'teacherapp-f0907',
    storageBucket: 'teacherapp-f0907.appspot.com',
    iosBundleId: 'com.example.teacherapp.RunnerTests',
  );
}
